repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
        -   id: trailing-whitespace
        -   id: mixed-line-ending
        -   id: check-case-conflict
        -   id: check-symlinks
        -   id: detect-aws-credentials

  -   repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
        -   id: black
        -   id: black-jupyter

  -   repo: https://github.com/roy-ht/pre-commit-jupyter
      rev: v1.2.1
      hooks:
        - id: jupyter-notebook-cleanup
          args:
            # - --remove-kernel-metadata
            - --pin-patterns
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.971
      hooks:
      -   id: mypy
